<?php

namespace SNT\DarmankoBundle\Repository;

/**
 * BienRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($localite, $type, $budget)
    {
        $query = $this->createQueryBuilder('b')
        ->join('b.localite', 'l')
        ->join('b.type', 't')
        ->addSelect('l')
        ->addSelect('t')
        ->WHERE('l.id = :localite OR t.id = :type OR b.prixLocation BETWEEN :prixMin AND :prixMax')
        ->setParameters(array('localite' => $localite, 'type' => $type, 'prixMin' => $budget - 10000, 'prixMax' => $budget + 20000));

        return $query->getQuery()->getResult();
    }

    public function findBiens($idLocalite = 0, $idType = 0, $budget = 0)
    {
        $dql = "SELECT b, i FROM SNT\DarmankoBundle\Entity\Bien b 
        left Join b.images i Join b.type t Join b.localite l WHERE b.etat = 1";
        if ($idLocalite != 0) {
            $dql .= ' AND l.id = :idLoc';
        }
        if ($idType != 0) {
            $dql .= ' AND t.id = :idType';
        }
        if ($budget != 0) {
            $dql .= ' AND b.prixLocation BETWEEN :prixMin AND :prixMax';
        }

        $query = $this->getEntityManager()->createQuery($dql);

        if ($idLocalite != 0) {
            $query->setParameter('idLoc', $idLocalite);
        }
        if ($idType != 0) {
            $query->setParameter('idType', $idType);
        }
        if ($budget != 0) {
            $query->setParameter('prixMin', $budget - 10000)
            ->setParameter('prixMax', $budget + 20000);
        }

        return $query->getResult();
    }
}
