<?php

namespace SNT\DarmankoBundle\Repository;

/**
 * BienRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($localite, $type)
    {
        $query = $this->createQueryBuilder('b')
        ->join('b.localite', 'l')
        ->join('b.type', 't')
        ->addSelect('l')
        ->addSelect('t')
        ->WHERE('l.id = :localite OR t.id = :type')
        ->setParameters(array('localite' => $localite, 'type' => $type));

        return $query->getQuery()->getResult();
    }
}
